version: "3"
services:
  mysql:
    build: db/
    container_name: mysql
    volumes:
      - Database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<DB_ROOT_PASS>
      - MYSQL_USER=<DB_USER>
      - MYSQL_PASSWORD=<DB_PASS>
  web:
    build: app/
    container_name: web
    ports:
      - "8080:8080"
    volumes:
      - Webapps:/usr/local/tomcat/webapps
    links:
      - mysql
    environment:
      - DB_USER=<DB_USER>
      - DB_PASS=<DB_PASS>
  jenkins:
    build: jenkins/
    container_name: jenkins
    ports:
      - "8090:8080"
    volumes:
      - JenkinsHome:/var/jenkins_home
    links:
      - mysql
      - web
volumes:
  Database: {}
  Webapps: {}
  JenkinsHome: {}
