version: "3"
services:
  mysql:
    build: db/
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=jspcrud
      - MYSQL_PASSWORD=Aa123456
  web:
    build: app/
    container_name: web
    ports:
      - "8080:8080"
    # volumes:
    #   - DataVolume1:/usr/local/tomcat
    links:
      - mysql
    environment:
      - DB_USER=jspcrud
      - DB_PASS=Aa123456
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8090:8080"
    # volumes:
    #   - DataVolume1:/usr/local/tomcat
    links:
      - mysql
      - web
# volumes:
#   DataVolume1: {}
